import os
import random
import time

# =========================
# Scanner Agent
# =========================
class Scanner:
    def __init__(self, root_path):
        self.root_path = root_path

    def scan(self):
        print("\n[Scanner Agent] Starting disk scan...")
        files = []

        # 只扫描少量，避免卡死
        for root, dirs, filenames in os.walk(self.root_path):
            for name in filenames:
                path = os.path.join(root, name)
                try:
                    size = os.path.getsize(path)
                    files.append((path, size))
                except:
                    continue

                if len(files) > 30:  # 限制数量（演示用）
                    return files
        return files


# =========================
# Analyzer Agent（核心Token消耗）
# =========================
class Analyzer:
    def analyze(self, file_path, size):
        print(f"\n[Analyzer Agent] Analyzing file:")
        print(f"  → Path: {file_path}")
        print(f"  → Size: {round(size/1024,2)} KB")

        # 模拟AI推理时间
        time.sleep(0.5)

        # 模拟Token消耗
        tokens = random.randint(1200, 2800)

        print(f"  → Calling AI model (MiMo/GPT-like)...")
        time.sleep(0.3)
        print(f"  → Token usage: {tokens}")

        # 模拟语义判断
        keywords = ["cache", "temp", "log", "tmp"]
        if any(k in file_path.lower() for k in keywords):
            decision = "LIKELY_TEMP_FILE"
            reason = "File appears to be temporary/cache generated by applications."
        else:
            decision = "UNCERTAIN"
            reason = "File role unclear, requires cautious handling."

        print(f"  → Reasoning: {reason}")
        print(f"  → Classification: {decision}")

        return decision, tokens


# =========================
# Executor Agent（安全执行）
# =========================
class Executor:
    def __init__(self, safe_mode=True):
        self.safe_mode = safe_mode
        self.total_tokens = 0

    def execute(self, file_path, decision, tokens):
        self.total_tokens += tokens

        print(f"\n[Executor Agent] Decision Phase")

        if decision == "LIKELY_TEMP_FILE":
            print("  → Strategy: Mark for cleanup")

            if self.safe_mode:
                print(f"  → [SAFE MODE] Would delete: {file_path}")
            else:
                print(f"  → Deleting: {file_path}")
                # ⚠️ 真删除（默认不会走到这里）
                # os.remove(file_path)

        else:
            print("  → Strategy: Skip (low confidence)")

        print("  → Execution complete\n")


# =========================
# 主流程（多Agent协作）
# =========================
def main():
    print("=" * 50)
    print(" AI Multi-Agent Cleaner System (Demo Mode)")
    print("=" * 50)

    scanner = Scanner("C:\\")
    analyzer = Analyzer()
    executor = Executor(safe_mode=True)  # ✅ 默认安全模式

    files = scanner.scan()

    print(f"\n[System] Total files sampled: {len(files)}")

    for file_path, size in files:
        decision, tokens = analyzer.analyze(file_path, size)
        executor.execute(file_path, decision, tokens)

    print("\n" + "=" * 50)
    print("[Summary]")
    print(f"Total Token Consumption: {executor.total_tokens}")
    print("Mode: SAFE (No real deletion)")
    print("=" * 50)


if __name__ == "__main__":
    main()
